/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DAO_HocVien;
import DAO.DAO_KhoaHoc;
import DAO.DAO_NguoiHoc;
import Model.HocVien;
import Model.KhoaHoc;
import Model.NguoiHoc;
import java.awt.event.ItemEvent;
import static java.nio.file.Files.list;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrmHocVien extends javax.swing.JFrame {

    /**
     * Creates new form FrmHocVien
     */
    int makh;
    DAO_NguoiHoc daoNh = new DAO_NguoiHoc();
    DAO_HocVien daoHv = new DAO_HocVien();
    DAO_KhoaHoc daoKh = new DAO_KhoaHoc();

    public FrmHocVien(int makh) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        fillKhoaHoc();        
        this.makh = makh;        
        fillComboBox();       
        loadHocVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cbbHocVien = new javax.swing.JComboBox<>();
        txtMarks = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        cbbKhoaHoc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHocVien = new javax.swing.JTable();
        radAll = new javax.swing.JRadioButton();
        radMarked = new javax.swing.JRadioButton();
        radNotMarks = new javax.swing.JRadioButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ HỌC VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("HỌC VIÊN CỦA KHÓA");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbbHocVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbHocVienActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        cbbKhoaHoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbKhoaHocItemStateChanged(evt);
            }
        });
        cbbKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbKhoaHocMouseClicked(evt);
            }
        });
        cbbKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbKhoaHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cbbHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbbKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnThem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMarks, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(btnThem))
                    .addComponent(cbbHocVien)
                    .addComponent(cbbKhoaHoc))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("HỌC VIÊN KHÁC");

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Học viên", "Mã Người học", "Họ Và Tên", "Điểm", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbHocVien);

        radAll.setSelected(true);
        radAll.setText("Tất cả");
        radAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAllActionPerformed(evt);
            }
        });

        radMarked.setText("Đã nhập điểm");
        radMarked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMarkedActionPerformed(evt);
            }
        });

        radNotMarks.setText("Chưa nhập điểm");
        radNotMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNotMarksActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập nhập");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radMarked)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radNotMarks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radAll)
                    .addComponent(radMarked)
                    .addComponent(radNotMarks)
                    .addComponent(btnUpdate))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbHocVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbHocVienActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void cbbKhoaHocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbKhoaHocItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {            
            KhoaHoc kh = (KhoaHoc) cbbKhoaHoc.getSelectedItem();
            makh = kh.getMaKhoaHoc();
            System.out.println(cbbKhoaHoc.getSelectedItem());
            fillComboBox();
            loadHocVien();
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            //Do any operations you need to do when an item is de-selected.
        }
    }//GEN-LAST:event_cbbKhoaHocItemStateChanged

    private void cbbKhoaHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbKhoaHocMouseClicked

    }//GEN-LAST:event_cbbKhoaHocMouseClicked

    private void cbbKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbKhoaHocActionPerformed

    }//GEN-LAST:event_cbbKhoaHocActionPerformed

    private void radAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAllActionPerformed
        loadHocVien();
    }//GEN-LAST:event_radAllActionPerformed

    private void radMarkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMarkedActionPerformed
        loadHocVien();
    }//GEN-LAST:event_radMarkedActionPerformed

    private void radNotMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNotMarksActionPerformed
        loadHocVien();
        KhoaHoc kh = (KhoaHoc) cbbKhoaHoc.getSelectedItem();
        makh = kh.getMaKhoaHoc();
        System.out.println(cbbKhoaHoc.getSelectedItem());
        fillComboBox();
        loadHocVien();
    }//GEN-LAST:event_radNotMarksActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    public void fillComboBox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbHocVien.getModel();
        model.removeAllElements();
        
        try {
            ArrayList<NguoiHoc> list = daoNh.selectNyCourse(makh);
            for (NguoiHoc nguoiHoc : list) {
                model.addElement(nguoiHoc);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn");
            e.printStackTrace();
        }
    }
    
    public void fillKhoaHoc() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model = (DefaultComboBoxModel) cbbKhoaHoc.getModel();
        model.removeAllElements();
        
        try {
            ArrayList<KhoaHoc> list = daoKh.select();
            for (KhoaHoc khoaHoc : list) {
                model.addElement(khoaHoc);
            }
            
        } catch (Exception e) {
        }
    }
    
    public void loadHocVien() {
        DefaultTableModel model = (DefaultTableModel) tbHocVien.getModel();
        model.setRowCount(0);
        
        try {
            String sql = "SELECT MaHocVien, HocVien.MaNguoiHoc, HoTen, DiemTrungBinh from HocVien join NguoiHoc on HocVien.MaNguoiHoc = NguoiHoc.MaNguoiHoc where MaKhoaHoc = ?";
            ResultSet rs = jdbcHelper.JdbcHelper.executeQuery(sql, makh);
            while (rs.next()) {
                Object[] row = {
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getDouble(4),
                    false
                };
                
                if (radAll.isSelected()) {
                    model.addRow(row);
                } else if (radMarked.isSelected() && rs.getDouble(4) >= 0) {
                    model.addRow(row);
                } else if (radNotMarks.isSelected() && rs.getDouble(4) < 0) {
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
    }
    
    public void insert() {
        if (check()) {
            NguoiHoc nguoiHoc = (NguoiHoc) cbbHocVien.getSelectedItem();
            
            HocVien hv = new HocVien();
            hv.setMaKhoaHoc(makh);
            hv.setMaNguoiHoc(nguoiHoc.getMaNguoiHoc());
            hv.setDiem(Double.parseDouble(txtMarks.getText()));
            
            try {
                daoHv.insert(hv);
                fillComboBox();
                loadHocVien();
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi thêm học viên vào khóa học");
                e.printStackTrace();
            }
        }
        
    }
    
    public void update() {
        for (int i = 0; i < tbHocVien.getRowCount(); i++) {
            Integer mahv = (Integer) tbHocVien.getValueAt(i, 0);
            String manh = (String) tbHocVien.getValueAt(i, 1);
            double diem = Double.parseDouble(String.valueOf(tbHocVien.getValueAt(i, 3)));
            boolean isDelete = (Boolean) tbHocVien.getValueAt(i, 4);
            
            if (isDelete) {
                daoHv.delete(mahv);
            } else {
                HocVien model = new HocVien();
                KhoaHoc kh = (KhoaHoc) cbbKhoaHoc.getSelectedItem();
                makh = kh.getMaKhoaHoc();
                model.setMaHocVien(mahv);
                model.setMaNguoiHoc(manh);
                model.setMaKhoaHoc(makh);
                model.setDiem(diem);
                
                daoHv.update(model);
            }
        }
        
        fillComboBox();
        loadHocVien();
        JOptionPane.showMessageDialog(this, "Cập nhập thành công");
    }
    
    public boolean check() {
        if (Double.parseDouble(txtMarks.getText()) < 0 || Double.parseDouble(txtMarks.getText()) > 10) {
            JOptionPane.showMessageDialog(this, "Điểm phải từ 0 - 10");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmHocVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmHocVien().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbbHocVien;
    private javax.swing.JComboBox<String> cbbKhoaHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radAll;
    private javax.swing.JRadioButton radMarked;
    private javax.swing.JRadioButton radNotMarks;
    private javax.swing.JTable tbHocVien;
    private javax.swing.JTextField txtMarks;
    // End of variables declaration//GEN-END:variables
}
