/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DAO_ChuyenDe;
import Model.ChuyenDe;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdbcHelper.ShareHelper;

/**
 *
 * @author Admin
 */
public class PalChuyenDe extends javax.swing.JPanel {

    /**
     * Creates new form PalChuyenDe
     */
    private Connection con;
    DefaultTableModel model = new DefaultTableModel();
    ArrayList<ChuyenDe> listChuyenDe = new ArrayList<>();
    private DAO_ChuyenDe dao = new DAO_ChuyenDe();
    String avatar = null;
    int index;
    
    public PalChuyenDe() {
        initComponents();
        loadDanhSach();
        setStatus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        txtMaChuyenDe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenChuyenDe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtThoiLuong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLLast = new javax.swing.JButton();
        lblPresent = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbChuyenDe = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(942, 599));

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý Chuyên đề");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Hình Logo");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        jLabel4.setText("Mô tả chuyên đề");

        jScrollPane1.setViewportView(txtMota);

        jLabel5.setText("Mã chuyên đề");

        jLabel6.setText("Tên chuyên đề");

        jLabel7.setText("Thời lượng");

        jLabel8.setText("Học phí");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnFirst.setBackground(new java.awt.Color(255, 153, 204));
        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 0, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/first.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(204, 51, 255));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/last.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLLast.setBackground(new java.awt.Color(204, 51, 255));
        btnLLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        btnLLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLLastActionPerformed(evt);
            }
        });

        lblPresent.setText("....");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5)
                                            .addComponent(txtMaChuyenDe)
                                            .addComponent(jLabel6)
                                            .addComponent(txtTenChuyenDe)
                                            .addComponent(jLabel7)
                                            .addComponent(txtThoiLuong)
                                            .addComponent(jLabel8)
                                            .addComponent(txtHocPhi, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnFirst)
                                        .addGap(40, 40, 40)
                                        .addComponent(btnBack)
                                        .addGap(61, 61, 61)
                                        .addComponent(lblPresent)
                                        .addGap(67, 67, 67)
                                        .addComponent(btnNext)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLLast)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(22, 22, 22))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLLast, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblPresent))
                            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFirst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chuyên Đề", jPanel2);

        tbChuyenDe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã chuyên đề", "Tên chuyên đề", "Thời lượng", "Học phí", "Hình", "Mô tả"
            }
        ));
        tbChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChuyenDeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbChuyenDe);
        if (tbChuyenDe.getColumnModel().getColumnCount() > 0) {
            tbChuyenDe.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbChuyenDe.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbChuyenDe.getColumnModel().getColumn(2).setResizable(false);
            tbChuyenDe.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbChuyenDe.getColumnModel().getColumn(3).setPreferredWidth(50);
            tbChuyenDe.getColumnModel().getColumn(4).setResizable(false);
            tbChuyenDe.getColumnModel().getColumn(4).setPreferredWidth(70);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addChuyenDe();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        index = 0;
        //edit();
        showDetail(index);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (index > 0) {
            index--;
            showDetail(index);
        } else {
            index = listChuyenDe.size() - 1;
            showDetail(index);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (index < listChuyenDe.size() - 1) {
            index++;
            showDetail(index);
        } else {
            index = 0;
            showDetail(index);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLLastActionPerformed
        index = listChuyenDe.size() - 1;
        showDetail(index);
    }//GEN-LAST:event_btnLLastActionPerformed
    

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        selectImage();
    }//GEN-LAST:event_lblImageMouseClicked

    private void tbChuyenDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChuyenDeMouseClicked
        int row = tbChuyenDe.getSelectedRow();
        if (row >= 0) {
            index = row;
            //this.edit();
            jTabbedPane1.setSelectedIndex(0);
            showDetail(index);
            setStatus(false);
        }
    }//GEN-LAST:event_tbChuyenDeMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        index = tbChuyenDe.getSelectedRow();
        if (index >= 0) {
            updateChuyenDe();
            showDetail(index);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        index = tbChuyenDe.getSelectedRow();
        if (index >= 0) {
            int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");
            if (choose == JOptionPane.YES_OPTION) {
                deleteChuyenDe();
                showDetail(index);
            }
        } else {
            setStatus(false);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
        lblPresent.setText("...");
    }//GEN-LAST:event_btnClearActionPerformed
    
    public void loadDanhSach() {
        model = (DefaultTableModel) tbChuyenDe.getModel();
        model.setRowCount(0);
        
        listChuyenDe = dao.select();
        
        for (ChuyenDe cd : listChuyenDe) {
            Object[] row = new Object[]{
                cd.getMaChuyenDe(), cd.getTenChuyenDe(), cd.getThoiLuong(), cd.getHocPhi(), cd.getHinh(), cd.getMoTa()
            };
            model.addRow(row);
        }

        // tbChuyenDe.setRowSelectionInterval(0, 0);
    }
    
    public void addChuyenDe() {
        if (check()) {
            ChuyenDe cd = getModel();
            try {
                dao.insert(cd);
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadDanhSach();
                clear();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                ex.printStackTrace();
            }
        }
        
    }
    
    public void updateChuyenDe() {
        if (check()) {
            ChuyenDe cd1 = getModel();
            try {
                dao.update(cd1);
                JOptionPane.showMessageDialog(this, "Update thành công");
                loadDanhSach();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Update thất bại");
                ex.printStackTrace();
            }
        }
        
    }
    
    public void clear() {
        setModel(new ChuyenDe());
        setStatus(true);
    }
    
    public void edit() {
        try {
            String maCD = tbChuyenDe.getValueAt(index, 0).toString();
            ChuyenDe model = dao.findbyID(maCD);
            setModel(model);
            setStatus(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lối truy ván dũ liệu");
            ex.printStackTrace();
        }
        
    }
    
    public void deleteChuyenDe() {
        
        try {
            String ma = txtMaChuyenDe.getText();
            dao.delete(ma);
            loadDanhSach();
            clear();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
            e.printStackTrace();
        }
        
    }
    
    public void showDetail(int index) {
        Model.ChuyenDe cd = listChuyenDe.get(index);
        lblImage.setToolTipText(cd.getHinh());

        //lblImage.setIcon(ShareHelper.readLogo(cd.getHinh()));
        upAvatar(cd.getHinh());
        
        txtMaChuyenDe.setText(cd.getMaChuyenDe());
        txtTenChuyenDe.setText(cd.getTenChuyenDe());
        txtThoiLuong.setText(cd.getThoiLuong() + "");
        txtHocPhi.setText(cd.getHocPhi() + "");
        txtMota.setText(cd.getMoTa());
        lblPresent.setText((index + 1) + " of " + listChuyenDe.size());
        
        tbChuyenDe.setRowSelectionInterval(index, index);
    }
    
    public void disbled() {
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);
        btnClear.setEnabled(false);
        btnFirst.setEnabled(false);
        btnBack.setEnabled(false);
        btnNext.setEnabled(false);
        btnLLast.setEnabled(false);
    }
    
    public void enabled() {
        btnSave.setEnabled(true);
        btnDelete.setEnabled(true);
        btnClear.setEnabled(true);
        btnFirst.setEnabled(true);
        btnBack.setEnabled(true);
        btnNext.setEnabled(true);
        btnLLast.setEnabled(true);
    }
    
    public void setModel(ChuyenDe model) {
        
        txtMaChuyenDe.setText(model.getMaChuyenDe());
        txtTenChuyenDe.setText(model.getTenChuyenDe());
        txtThoiLuong.setText(Integer.toString(model.getThoiLuong()));
        txtHocPhi.setText(Double.toString(model.getHocPhi()));
        lblImage.setToolTipText(model.getHinh());
        
        if (model.getHinh() != null) {
            lblImage.setIcon(ShareHelper.readLogo(model.getHinh()));
            upAvatar(model.getHinh());
        }
        txtMota.setText(model.getMoTa());
    }
    
    public ChuyenDe getModel() {
        ChuyenDe model = new ChuyenDe();
        model.setMaChuyenDe(txtMaChuyenDe.getText());
        model.setTenChuyenDe(txtTenChuyenDe.getText());
        model.setThoiLuong(Integer.parseInt(txtThoiLuong.getText()));
        model.setHocPhi(Double.parseDouble(txtHocPhi.getText()));
        model.setHinh(lblImage.getToolTipText());
        model.setMoTa(txtMota.getText());
        
        return model;
    }
    
    public void setStatus(boolean stt) {
        if (ShareHelper.ROLE) {
            btnAdd.setEnabled(stt);
            txtMaChuyenDe.setEditable(stt);
            btnSave.setEnabled(!stt);
            btnDelete.setEnabled(!stt);
            
            btnFirst.setEnabled(!stt);
            btnBack.setEnabled(!stt);
            btnNext.setEnabled(!stt);
            btnLLast.setEnabled(!stt);
        } else {
            btnAdd.setEnabled(stt);
            txtMaChuyenDe.setEditable(stt);
            btnSave.setEnabled(!stt);
            btnDelete.setEnabled(false);
            
            btnFirst.setEnabled(!stt);
            btnBack.setEnabled(!stt);
            btnNext.setEnabled(!stt);
            btnLLast.setEnabled(!stt);
        }
        
    }
    
    public void upAvatar(String fileName) {
        
        ImageIcon icon = ShareHelper.readLogo(fileName);
        Image image = icon.getImage();
        ImageIcon icon1 = new ImageIcon(image.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), image.SCALE_SMOOTH));
        lblImage.setIcon(icon1);
    }
    
    private void selectImage() {
        JFileChooser fileChoose = new JFileChooser("Du an mau\\");
        int result = fileChoose.showOpenDialog(fileChoose);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChoose.getSelectedFile();
            //avatar = file.getName();
//            upAvatar(avatar);

            if (ShareHelper.saveLogo(file)) {
                upAvatar(file.getName());
//                ImageIcon icon = ShareHelper.readLogo(file.getName());
//                Image image = icon.getImage();
//                ImageIcon icon1 = new ImageIcon(image.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), image.SCALE_SMOOTH));
//                lblImage.setIcon(icon1);
                lblImage.setToolTipText(file.getName());
            }
            
        }
    }
    
    public boolean check() {
        if (txtMaChuyenDe.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã chuyên đề không dc để trống");
            txtMaChuyenDe.requestFocus();
            return false;
        }
        if (txtTenChuyenDe.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tên chyên đề không dc để trống");
            txtTenChuyenDe.requestFocus();
            return false;
        }
        
        if (txtHocPhi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Học phí không dc để trống");
            txtHocPhi.requestFocus();
            return false;
        } else {
            if ((Double.parseDouble(txtHocPhi.getText())) < 0) {
                JOptionPane.showMessageDialog(this, "Học phí phải lớn hơn 0");
                return false;
            }
        }
        if (txtThoiLuong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Thời lượng không dc để trống");
            txtHocPhi.requestFocus();
            return false;
        } else {
            if ((Double.parseDouble(txtThoiLuong.getText())) < 0) {
                JOptionPane.showMessageDialog(this, "Thời lượng không dc nhỏ hơn 0");
                return false;
            }
        }
        
        if (lblImage.getToolTipText() == null) {
            JOptionPane.showMessageDialog(this, "Hình ko dc để trống");
            return false;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JTable tbChuyenDe;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtMaChuyenDe;
    private javax.swing.JTextPane txtMota;
    private javax.swing.JTextField txtTenChuyenDe;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables

}
