/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DAO_ChuyenDe;
import DAO.DAO_KhoaHoc;
import Model.ChuyenDe;
import Model.KhoaHoc;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import jdbcHelper.DateHelper;
import jdbcHelper.ShareHelper;

/**
 *
 * @author Admin
 */
public final class PalKhoaHoc extends javax.swing.JPanel {

    /**
     * Creates new form PalKhoaHoc
     */
    DAO.DAO_KhoaHoc daoKH = new DAO_KhoaHoc();
    DAO.DAO_ChuyenDe daoCD = new DAO_ChuyenDe();
    private final Connection con = null;
    ArrayList<Model.ChuyenDe> listChuyenDe = new ArrayList<>();
    int index;
    
    public PalKhoaHoc() {
        initComponents();
        loadChuyenDe();
        loadKhoaHoc();
        selectComboBox();
        clear();
        setStatus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbbChuyenDe = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        txtThoiLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNguoiTao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextPane();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnFisrt = new javax.swing.JButton();
        txtNgayKhaiGiang = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        btnHocVien = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhoaHoc = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý Khóa Học");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel2.setText("Chuyên đề");

        jLabel3.setText("Ngày khai giảng");

        cbbChuyenDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbChuyenDe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbChuyenDeItemStateChanged(evt);
            }
        });
        cbbChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbChuyenDeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbChuyenDeMousePressed(evt);
            }
        });
        cbbChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChuyenDeActionPerformed(evt);
            }
        });

        jLabel4.setText("Học phí");

        jLabel5.setText("Thời lượng (giờ)");

        jLabel6.setText("Người tạo");

        jLabel7.setText("Ngày tạo");

        jLabel8.setText("Ghi chú");

        jScrollPane1.setViewportView(txtGhiChu);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setText("<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnFisrt.setText("|<");
        btnFisrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFisrtActionPerformed(evt);
            }
        });

        btnHocVien.setText("Hoc Vien");
        btnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNguoiTao)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtHocPhi, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbbChuyenDe, javax.swing.GroupLayout.Alignment.LEADING, 0, 322, Short.MAX_VALUE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)))
                            .addGap(29, 29, 29)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(txtThoiLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(txtNgayKhaiGiang)
                                .addComponent(txtNgayTao)))
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoi)
                        .addGap(27, 27, 27)
                        .addComponent(btnHocVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(btnFisrt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack)
                        .addGap(51, 51, 51)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLast)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayKhaiGiang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnMoi)
                    .addComponent(btnLast)
                    .addComponent(btnNext)
                    .addComponent(btnBack)
                    .addComponent(btnFisrt)
                    .addComponent(btnHocVien))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cập nhập", jPanel3);

        tbKhoaHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khóa Học", "Mã Chuyên Đề", "Ngày tạo", "Ngày khai giảng", "Nhân viên", "Ghi chú"
            }
        ));
        tbKhoaHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhoaHocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKhoaHoc);
        if (tbKhoaHoc.getColumnModel().getColumnCount() > 0) {
            tbKhoaHoc.getColumnModel().getColumn(0).setPreferredWidth(35);
            tbKhoaHoc.getColumnModel().getColumn(1).setPreferredWidth(35);
            tbKhoaHoc.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbKhoaHoc.getColumnModel().getColumn(3).setPreferredWidth(50);
            tbKhoaHoc.getColumnModel().getColumn(4).setPreferredWidth(35);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách", jPanel4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbKhoaHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhoaHocMouseClicked
        int row = tbKhoaHoc.getSelectedRow();
        if (row >= 0) {
            index = row;
            edit();
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tbKhoaHocMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnFisrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFisrtActionPerformed
        index = 0;
        edit();
    }//GEN-LAST:event_btnFisrtActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        index--;
        edit();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        index++;
        edit();

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        index = tbKhoaHoc.getRowCount() - 1;
        edit();

    }//GEN-LAST:event_btnLastActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void cbbChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChuyenDeActionPerformed

    }//GEN-LAST:event_cbbChuyenDeActionPerformed

    private void cbbChuyenDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbChuyenDeMouseClicked

    }//GEN-LAST:event_cbbChuyenDeMouseClicked

    private void cbbChuyenDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbChuyenDeMousePressed

    }//GEN-LAST:event_cbbChuyenDeMousePressed

    private void btnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocVienActionPerformed
        //palChinh.setLayout(new CardLayout());
        int makh = (Integer) tbKhoaHoc.getValueAt(index, 0);
//        PalHocVien hv = new PalHocVien();
//        hv.setVisible(true);
        //System.out.println("Show Frm Học Viên");
//       palChinh.removeAll();
//       palChinh.add(hv).setVisible(true);
//       palChinh.updateUI();

        new FrmHocVien(makh).setVisible(true);
    }//GEN-LAST:event_btnHocVienActionPerformed

    private void cbbChuyenDeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbChuyenDeItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            selectComboBox();
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            //Do any operations you need to do when an item is de-selected.
        }
    }//GEN-LAST:event_cbbChuyenDeItemStateChanged
    
    public void loadChuyenDe() {
        //ArrayList<Model.ChuyenDe> listChuyenDe = new ArrayList<>();
        listChuyenDe = daoCD.select();
        
        DefaultComboBoxModel cbModel = (DefaultComboBoxModel) cbbChuyenDe.getModel();
        cbModel.removeAllElements();
        for (ChuyenDe chuyenDe : listChuyenDe) {
            cbModel.addElement(chuyenDe);
        }
    }
    
    public void loadKhoaHoc() {
        DefaultTableModel model = (DefaultTableModel) tbKhoaHoc.getModel();
        model.setRowCount(0);
        try {
            ArrayList<KhoaHoc> list = daoKH.select();
            for (Model.KhoaHoc kh : list) {
                Object[] row = new Object[]{
                    kh.getMaKhoaHoc(),
                    kh.getMaChuyenDe(),
                    kh.getNgayTao(),
                    kh.getNgayKhaiGiang(),
                    kh.getMaNhanVien(),
                    kh.getGhiChu()
                };
                model.addRow(row);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
        
    }
    
    public void insert() {
        if (check()) {
            KhoaHoc kh = getModel();
            kh.setNgayTao(DateHelper.toString(new Date()));
            System.out.println(new Date());
            try {
                daoKH.insert(kh);
                loadKhoaHoc();
                JOptionPane.showMessageDialog(this, "Thêm khóa học thành công");

                //clear();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Thêm khóa học thất bại");
                ex.printStackTrace();
            }
        }
        
    }
    
    public void update() {
        if (check()) {
            KhoaHoc kh = getModel();
            try {
                daoKH.update(kh);
                JOptionPane.showMessageDialog(this, "Cập nhập thành công");
                loadKhoaHoc();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cập nhập thất bại");
                e.printStackTrace();
            }
        }
        
    }
    
    public void delete() {
        Integer maKh = Integer.valueOf(cbbChuyenDe.getToolTipText());
        try {
            daoKH.delete(maKh);
            loadKhoaHoc();
            clear();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
            e.printStackTrace();
        }
    }
    
    public KhoaHoc getModel() {
        //Calendar date = Calendar.getInstance();
        //String date = ((JTextField) txtNgayTao.getDateEditor().getUiComponent()).getText();
        //String date1 = ((JTextField) txtNgayKhaiGiang.getDateEditor().getUiComponent()).getText();
        KhoaHoc model = new KhoaHoc();
        ChuyenDe chuyenDe = (ChuyenDe) cbbChuyenDe.getSelectedItem();
        
        model.setMaChuyenDe(chuyenDe.getMaChuyenDe());
        model.setTenChuyenDe(chuyenDe.getTenChuyenDe());
        model.setNgayTao(txtNgayTao.getText());
        model.setNgayKhaiGiang(txtNgayKhaiGiang.getText());
        model.setMaNhanVien(txtNguoiTao.getText());
        model.setGhiChu(txtGhiChu.getText());
        model.setThoiLuong(Integer.parseInt(txtThoiLuong.getText()));
        model.setHocPhi(Double.parseDouble(txtHocPhi.getText()));
        model.setMaKhoaHoc(Integer.valueOf(cbbChuyenDe.getToolTipText()));

        //System.out.println(model);
        //System.out.println(cbbChuyenDe.getToolTipText());
        return model;
    }
    
    public void setModel(KhoaHoc model) {
        //System.out.println(model);

        ChuyenDe chuyenDe = (ChuyenDe) cbbChuyenDe.getSelectedItem();
        //ChuyenDe chuyenDe1 = daoCD.findbyID(model.getMaChuyenDe());
        //System.out.println(chuyenDe1);
        cbbChuyenDe.setToolTipText(String.valueOf(model.getMaKhoaHoc()));
        //cbbChuyenDe.setSelectedItem(model.getTenChuyenDe());
        cbbChuyenDe.getModel().setSelectedItem(daoCD.findbyID(model.getMaChuyenDe()));
        
//        for (int i = 0; i < listChuyenDe.size(); i++) {
//            if (chuyenDe1.equals(listChuyenDe.get(i))) {
//                cbbChuyenDe.setSelectedItem(listChuyenDe.get(i).getTenChuyenDe());
//            }
// 
//        }
        txtNgayKhaiGiang.setText(model.getNgayKhaiGiang());
        txtNguoiTao.setText(ShareHelper.USER.getMaNhanVien());
        txtNgayTao.setText(model.getNgayTao());
        txtGhiChu.setText(model.getGhiChu());
        txtThoiLuong.setText(Integer.toString(chuyenDe.getThoiLuong()));
        txtHocPhi.setText(Double.toString(chuyenDe.getHocPhi()));
    }
    
    public void clear() {
        KhoaHoc kh = new KhoaHoc();
        ChuyenDe cd = (ChuyenDe) cbbChuyenDe.getSelectedItem();
        
        kh.setMaChuyenDe(cd.getMaChuyenDe());
        kh.setTenChuyenDe(cd.getTenChuyenDe());
        kh.setNgayTao(DateHelper.toString(new Date()));
        kh.setNgayKhaiGiang(DateHelper.toString(DateHelper.add(20)));
        kh.setMaNhanVien(txtNguoiTao.getText());
        kh.setGhiChu(txtGhiChu.getText());
        this.setModel(kh);
        setStatus(true);
    }
    
    public void edit() {
        try {
            Integer maKh = (Integer) tbKhoaHoc.getValueAt(index, 0);
            KhoaHoc model = daoKH.findById(maKh);
            if (model != null) {
                this.setModel(model);
                this.setStatus(false);
                tbKhoaHoc.setRowSelectionInterval(index, index);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy ván dư liệu");
            e.printStackTrace();
        }
    }
    
    public void setStatus(boolean stt) {
        if (ShareHelper.ROLE) {
            btnThem.setEnabled(stt);
            btnSua.setEnabled(!stt);
            btnXoa.setEnabled(!stt);
            btnNext.setEnabled(!stt);
            btnLast.setEnabled(!stt);
            btnBack.setEnabled(!stt);
            btnFisrt.setEnabled(!stt);
            
            btnHocVien.setVisible(!stt);
        } else {
            btnThem.setEnabled(stt);
            btnSua.setEnabled(!stt);
            btnXoa.setEnabled(false);
            btnNext.setEnabled(!stt);
            btnLast.setEnabled(!stt);
            btnBack.setEnabled(!stt);
            btnFisrt.setEnabled(!stt);
            
            btnHocVien.setVisible(!stt);
        }
    }
    
    public void selectComboBox() {
        ChuyenDe cd = (ChuyenDe) cbbChuyenDe.getSelectedItem();
        txtThoiLuong.setText(String.valueOf(cd.getThoiLuong()));
        txtHocPhi.setText(String.valueOf(cd.getHocPhi()));
    }
    
    public boolean check() {
        Date date2 = DateHelper.toDate(txtNgayTao.getText());
        Date date1 = DateHelper.toDate(txtNgayKhaiGiang.getText());
        if (date1.compareTo(date2) < 0) {
            JOptionPane.showMessageDialog(this, "Ngày khai giảng không dc nhỏ hưn ngày tạo");
            txtNgayKhaiGiang.requestFocus();
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFisrt;
    private javax.swing.JButton btnHocVien;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbChuyenDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbKhoaHoc;
    private javax.swing.JTextPane txtGhiChu;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtNgayKhaiGiang;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNguoiTao;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables
}
